### ISSUE TITLE
Error - Wont start game

### ISSUE THREAD

**Issue by Saphiria** [j0ach1mmall3/KFA#13]
Heres the error. http://pastebin.com/1ypPdGuW @j0ach1mmall3 @nfelly @Fireflies @Fireflies @Blackfatrat

**Comment by Fireflies** [comment]
>This paste has been removed

Any chance you could re-post it? :P 
I blame @j0ach1mmall3 because I said I didn't have a chance to test it but he merged it regardless :sweat_smile: :wink:

**Comment by j0ach1mmall3** [comment]
Oi paste not available anymore gg.
Anyways, when I finished my UltimateCosmetics plugin I will look into it.
Also, why did @Fireflies get 2 tags? ;-;

**Comment by Fireflies** [comment]
Because I'm just that badass.

**Comment by Fireflies** [comment]
And because I'm the one who probably left the bug there lmao.

**Comment by j0ach1mmall3** [comment]
Well then fix it lol.

**Comment by Fireflies** [comment]
I did say it was untested in my PR >.> 
I'm out at the cinema right now and have been out the house since 11, will _probably_ take a look when home.

**Comment by Fireflies** [comment]
Marked as user error until further notice.
