### ISSUE TITLE
Bad .gitignore

### ISSUE THREAD

**Issue by acecheese** [j0ach1mmall3/KFA#3]
I mean really?

Github even has it's own fancy "create a .gitignore"....

**Comment by j0ach1mmall3** [comment]
What would I need it for?

**Comment by acecheese** [comment]
![](http://i.ac3-servers.eu/i/15-04-15_08-32-43.png)

I mean, they often cause issues whilst trying to fork.

**Comment by j0ach1mmall3** [comment]
I'll check it out

**Comment by j0ach1mmall3** [comment]
Puh, can't you create one? I don't know how to D:

**Comment by Saphiria** [comment]
Was this fixed?

**Comment by Fireflies** [comment]
Issue can be closed, updated appropriately in #10
